POST http://localhost:5000/api/send-otp HTTP/1.1
Content-Type: application/json

{
    "phone":"+8801718295833"
}

###
POST http://localhost:5000/api/verify-otp HTTP/1.1
Content-Type: application/json

{
    "username":"Shahrier Hossain Mahin",
    "password":"abcdefg",
    "email":"hossainshahrier.shm@gmail.com",
    "phone":"+8801718295833",
    "otp":7475,
    "hash":"ba7efedf544c797964e059805f25a846c7b8feecad74cd93f1666edec15a3a7a.1635586282504"
}